[workspace]
members = [
    "agent/agent-common",
    "agent/resource-agent",
    "agent/test-agent",
    "bottlerocket/agents",
    "bottlerocket/cli",
    "bottlerocket/types",
    "controller",
    "model",
    "selftest",
    "yamlgen",
]

resolver = "2"
