[package]
name = "bottlerocket-types"
version = "0.0.2"
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
configuration-build-derive = { path = "../../agent/configuration-build-derive"}
model = { version = "0.0.2", path = "../../model" }
serde = "1"
serde_plain = "1"
serde_yaml = "0.8"
serde_json = "1"
