[package]
name = "yamlgen"
version = "0.0.2"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[build-dependencies]
kube = { version = "0.74", default-features = false }
model = { version = "0.0.2", path = "../model" }
serde_yaml = "0.8"
