[package]
name = "yamlgen"
version = "0.1.0"
edition = "2018"
publish = false

[build-dependencies]
kube = { version = "0.59.0", default-features = true, features = [ "derive"] }
model = { path = "../model" }
serde_yaml = "0.8"
