[package]
name = "agent-common"
version = "0.0.5"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
testsys-model = { version = "0.0.5", path = "../../model" }
snafu = "0.7"

[dev-dependencies]
tempfile = "3"
