name: Images
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'design/**'
  push:
    paths-ignore:
      - '**.md'
      - 'design/**'
    branches: [develop, monorepo]
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable
      - run: make build
        # If we forget to add yamlgen changes to our commits, this will fail.
      - name: ensure that git is clean
        run: test -z "$(git status --untracked-files=all --porcelain)"
      - run: make controller
      - run: make duplicator-resource-agent
      - run: make example-resource-agent
      - run: make example-test-agent
      - run: make integ-test
        env:
          TESTSYS_SELFTEST_SKIP_IMAGE_BUILDS: true
          TESTSYS_SELFTEST_THREADS: 1
  images:
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - uses: actions/checkout@v3
      # TODO - for most PRs we should use the published container image instead of building each time
      - run: make tools -e TOOLS_IMAGE=localtools:latest
      - run: make images -e TOOLS_IMAGE=localtools:latest
  license-check:
    # A small machine is OK for this independent job.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable
      - run: make cargo-deny
